Navigation
automat-ed/autonomous pull request #30
Opened 2021-03-23 19:31 UTC by enzo-inc

This PR implements the navigation stack of the robot - Closes #14, Closes #15, Closes #16. 

More specifically, it makes use of: 
- The `map_server` package to produce an Occupancy Grid from an aerial shot of the environment; 
- The `costmap_2d` package - a dependency of `move_base` - to produce a local and a global Costmap from the Occupancy Grid
- The `navfn` package - a dependency of `move_base` - to provide a global path using Dijkstra's algorithm
- The `base_local_planner` package  - a dependency of `move_base` - to provide a local plan taking into account the global plan, the Costmaps, and the obstacles detected by the Lidar sensor

Finally, the ROS "navigation" package has been created to contain all the relevant files

2021-03-23 21:51 UTC, Siliconlad requested changes
This looks really good! Well done 🎉 Just a few suggestions. I'll test it out a little later before merging.

Also, what's the difference between `navigation.rviz` and `automated.rviz`?

2021-03-23 21:51 UTC, Siliconlad commented on launch/navigation.launch
> +    <arg name="ground_truth" default="false"/>
Would it be worth exposing all the `<args>` that `localization.launch` exposes? Because right now there are arguments you can't change via the command line, like the world that webots launches.

2021-03-23 21:51 UTC, Siliconlad commented on launch/navigation.launch
> +    <arg name="map_file" default="$(find navigation)/config/square.yaml"/>
This works, but it may be better if we parameterize just the name? Otherwise, we would need to enter the entire path (although this may be better practice), like I did with the rviz config. I don't see us using any other path than the `navigation/config` directory?

2021-03-23 21:51 UTC, Siliconlad commented on launch/navigation.launch
> +    <node pkg="move_base" type="move_base" respawn="false" name="move_base" output="screen">
I think `respawn` is set to false by default.

```suggestion
    <node pkg="move_base" type="move_base" name="move_base" output="screen">
```

2021-03-23 21:51 UTC, Siliconlad commented on launch/navigation.launch
> +</launch>
```suggestion
</launch>

```

2021-03-23 21:51 UTC, Siliconlad commented on src/navigation/CMakeLists.txt
> +  robot_localization
Do you need `robot_localization` in this package?

2021-03-23 21:51 UTC, Siliconlad commented on src/navigation/CMakeLists.txt
> +# )
```suggestion
```

2021-03-23 21:51 UTC, Siliconlad commented on src/navigation/config/costmap_common_params.yaml
> +                    clearing: true}
```suggestion
                    clearing: true}

```

2021-03-23 21:51 UTC, Siliconlad commented on src/navigation/config/costmap_common_params.yaml
> +# footprint_padding: 0.05
Any reason why these are commented out?

2021-03-23 21:51 UTC, Siliconlad commented on src/navigation/config/global_costmap_params.yaml
> +  static_map: true
```suggestion
  static_map: true
  
```

2021-03-23 21:51 UTC, Siliconlad commented on src/navigation/config/local_costmap_params.yaml
> +  # resolution: 0.098039216
```suggestion
  # resolution: 0.098039216
  
```

2021-03-23 21:51 UTC, Siliconlad commented on src/navigation/config/local_costmap_params.yaml
> +  # resolution: 0.098039216
Any reason why these are commented out?

2021-03-23 21:51 UTC, Siliconlad commented on src/navigation/config/square.yaml
> +mode: trinary
```suggestion
mode: trinary

```

2021-03-23 21:51 UTC, Siliconlad commented on src/navigation/package.xml
> +  <!--   <doc_depend>doxygen</doc_depend> -->
```suggestion
```

2021-03-23 21:51 UTC, Siliconlad commented on src/navigation/package.xml
> +
```suggestion
```

2021-03-25 09:29 UTC, enzo-inc commented
> This looks really good! Well done  Just a few suggestions. I'll test it out a little later before merging.
> 
> Also, what's the difference between `navigation.rviz` and `automated.rviz`?

Oops sorry, they are the exact same configuration. I will keep `navigation.rviz` and remove `automated.rviz`

2021-03-25 09:58 UTC, enzo-inc commented on src/navigation/config/costmap_common_params.yaml
> +# footprint_padding: 0.05
I was experimenting with those values and I thought it was worth it to keep them in case navigation needed to be tuned further

2021-03-25 10:00 UTC, enzo-inc commented on src/navigation/config/local_costmap_params.yaml
> +  # resolution: 0.098039216
Nope just forgot to delete them

2021-03-25 15:29 UTC, enzo-inc reviewed
Implemented requested changes

2021-03-25 15:30 UTC, enzo-inc reviewed
Implemented requested changes

2021-03-25 15:59 UTC, Siliconlad reviewed
What is the `frames.pdf`?

2021-03-25 15:59 UTC, Siliconlad commented on src/navigation/config/costmap_common_params.yaml
> +                    topic: /lidar/ground_truth,
Ground truth?

2021-03-25 17:35 UTC, Siliconlad approved these changes
Looks good!

@enzo-inc and I found a small problem where the robot position in the cost map in RViz and the robot in Webots don't match up (i.e the actual robot is on the left side of the simulation while in RViz it's on the right). But this doesn't seem to be consistent in that it looks off and then it look ok again. We're not sure why so we're just merging this and hope we can just deal with the problem.

2021-03-25 17:35 UTC, merged